"""add is_active to dialog_template

Revision ID: 0531817bf8e0
Revises: a3c6783ccb02
Create Date: 2026-03-16 11:38:44.875846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0531817bf8e0'
down_revision: Union[str, Sequence[str], None] = 'a3c6783ccb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog_template', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialog_template', 'is_active')
    # ### end Alembic commands ###
