"""add language to dialog_template

Revision ID: 6644c3ebba61
Revises: 0531817bf8e0
Create Date: 2026-03-16 14:51:20.426846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6644c3ebba61'
down_revision: Union[str, Sequence[str], None] = '0531817bf8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog_template', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialog_template', 'language')
    # ### end Alembic commands ###
