"""add retry_count and next_retry_at to task

Revision ID: 82ffd7b03b9b
Revises: 6a89d9209f17
Create Date: 2026-04-19 15:42:31.710807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82ffd7b03b9b'
down_revision: Union[str, Sequence[str], None] = '6a89d9209f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('task', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_next_retry_at'), 'task', ['next_retry_at'], unique=False)
    op.alter_column('task', 'retry_count', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_next_retry_at'), table_name='task')
    op.drop_column('task', 'next_retry_at')
    op.drop_column('task', 'retry_count')
    # ### end Alembic commands ###
