"""add password_changed_at to user

Revision ID: a251f22a133e
Revises: 3f88cf860e4c
Create Date: 2026-04-21 11:37:50.039465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a251f22a133e'
down_revision: Union[str, Sequence[str], None] = '3f88cf860e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_changed_at')
    # ### end Alembic commands ###
