"""add index on task scheduled_time

Revision ID: a3c6783ccb02
Revises: cb870bee6bfe
Create Date: 2026-03-15 10:02:46.823112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3c6783ccb02'
down_revision: Union[str, Sequence[str], None] = 'cb870bee6bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_scheduled_time'), 'task', ['scheduled_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_scheduled_time'), table_name='task')
    # ### end Alembic commands ###
