"""add user_rating columns to task

Revision ID: f6c0dd4e684b
Revises: 34fc389ea6e5
Create Date: 2026-04-19 17:49:40.640914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6c0dd4e684b'
down_revision: Union[str, Sequence[str], None] = '34fc389ea6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('user_rating_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_rating_comment')
    op.drop_column('task', 'user_rating')
    # ### end Alembic commands ###
