"""add local_recording_path to call_session

Revision ID: fc9ddc190cf9
Revises: 6644c3ebba61
Create Date: 2026-03-17 14:13:38.456935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc9ddc190cf9'
down_revision: Union[str, Sequence[str], None] = '6644c3ebba61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_session', sa.Column('local_recording_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_session', 'local_recording_path')
    # ### end Alembic commands ###
