"""Shared constants used across multiple modules."""

# Password validation
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128

# Slot data validation
MAX_SLOT_COUNT = 20
MAX_SLOT_KEY_LENGTH = 50
MAX_SLOT_VALUE_LENGTH = 500

# Template validation
TEMPLATE_NAME_MIN_LENGTH = 2
TEMPLATE_NAME_MAX_LENGTH = 100
TEMPLATE_SCRIPT_MIN_LENGTH = 10
TEMPLATE_SCRIPT_MAX_LENGTH = 5000

# Twilio call settings
GATHER_TIMEOUT_SECONDS = 8
CALL_ANSWER_TIMEOUT_SECONDS = 30
CALL_STATUS_POLL_INTERVAL_SECONDS = 1

# Audio
WAV_HEADER = b"RIFF"
AUDIO_SAMPLE_16BIT_MIN = -32768
AUDIO_SAMPLE_16BIT_MAX = 32767
FADE_DURATION_SECONDS = 0.3

# File upload
MAX_UPLOAD_SIZE_BYTES = 50 * 1024 * 1024  # 50 MB
